### ISSUE TITLE
Seeking further dataset(s) that will show fuzzy geometry to test the model

### ISSUE THREAD

**Issue by Metaduck** [idn-au/fuzzy-geometries#7]
4-Jun Would like another indigenous area that has probalistic boundaries to test the fuzzy geometries further. 
@Nick to follow up with Bruce on work that his PhD student [Sandy Potter] undertook on fuzzy geometries in the Kimberly. i.e. catographic maps vs digital representation - or even written descriptions.

**Comment by Metaduck** [comment]
Need to contact Bruce and Levi

**Comment by nicholascar** [comment]
Follow-up email to Bruce today

**Comment by Metaduck** [comment]
Have emailed Judy Melbourne at NPY and asked for help but no response so far. Will email again.
